services:
  - type: web
    name: cold-email-api
    env: node
    plan: starter
    buildCommand: npm install && npm run prisma:generate && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20
  - type: worker
    name: cold-email-worker
    env: node
    plan: starter
    buildCommand: npm install && npm run prisma:generate && npm run build
    startCommand: npm run start:worker
    envVars:
      - key: NODE_VERSION
        value: 20
  - type: worker
    name: cold-email-scheduler
    env: node
    plan: starter
    buildCommand: npm install && npm run prisma:generate && npm run build
    startCommand: npm run start:scheduler
    envVars:
      - key: NODE_VERSION
        value: 20
